name: Build library

on:
  push

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: threeal/cmake-action@v2.1.0
      with:
        build-dir: output-build
