name: Deploy Doxygen to Github Pages
author: Noah Reeder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Doxygen generation
        uses: mattnotmitt/doxygen-action@v1.9.8

      - name: Create artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output-doxygen/

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
